### ISSUE TITLE
importerror : cannot import name 'secure_write' #5

### ISSUE THREAD

**Issue by shreyasharma98** [medashiva/ubuntu-python3.6-installation#1]
I want to update my python version to python 3.6 , I am using conda environment therefore used the following command on the terminal : 
`conda install python=3.6` 

And hence encountered with this error : `importerror :  cannot import name 'secure_write'`
Any help???

**Comment by medashiva** [comment]
Hope you tried --> https://stackoverflow.com/questions/41535881/how-do-i-upgrade-to-python-3-6-with-conda

can you please provide more details.

**Comment by shreyasharma98** [comment]
Yeahh! I did this , but didnt helped!!
I am unable to use f'strings in python v - 3.5 , thus i tried to update the python version using the command  : `conda install python=3.6` 
while installation I am facing this bug!!
